"""initial

Revision ID: abf9649be742
Revises: 
Create Date: 2026-07-02 23:44:06.208444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf9649be742'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('DOCUMENT_UPLOADED', 'DOCUMENT_CLASSIFIED', 'CLASSIFICATION_OVERRIDDEN', 'DOCUMENT_MATCHED', 'DOCUMENT_REASSOCIATED', 'SHIPMENT_CREATED', 'SHIPMENT_STATUS_UPDATED', 'EMAIL_SYNCED', name='activityaction'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_org_id'), 'activity_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_shipment_id'), 'activity_logs', ['shipment_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_key', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('EMAIL', 'UPLOAD', name='documentsource'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'OCR_PENDING', 'OCR_PROCESSING', 'OCR_FAILED', 'CLASSIFIED', 'MATCHED', 'UNMATCHED', 'NEEDS_REVIEW', name='documentstatus'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_index(op.f('ix_documents_shipment_id'), 'documents', ['shipment_id'], unique=False)
    op.create_table('mailbox_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GMAIL', 'MICROSOFT365', 'OUTLOOK', 'IMAP', name='emailprovider'), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('access_token_enc', sa.String(length=2000), nullable=True),
    sa.Column('refresh_token_enc', sa.String(length=2000), nullable=True),
    sa.Column('imap_host', sa.String(length=255), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('imap_password_enc', sa.String(length=2000), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailbox_connections_org_id'), 'mailbox_connections', ['org_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETE', 'ON_HOLD', name='shipmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_org_id'), 'shipments', ['org_id'], unique=False)
    op.create_table('classification_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('COMMERCIAL_INVOICE', 'PACKING_LIST', 'BILL_OF_LADING', 'AIR_WAYBILL', 'CERTIFICATE_OF_ORIGIN', 'INSURANCE_CERTIFICATE', 'CUSTOMS_DECLARATION', 'PURCHASE_ORDER', 'DELIVERY_ORDER', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('classified_by', sa.UUID(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_results_document_id'), 'classification_results', ['document_id'], unique=True)
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_key', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('email_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('sender', sa.String(length=500), nullable=True),
    sa.Column('recipient', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['mailbox_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_email_records_org_id'), 'email_records', ['org_id'], unique=False)
    op.create_table('ocr_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_results_document_id'), 'ocr_results', ['document_id'], unique=True)
    op.create_table('shipment_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('associated_by', sa.UUID(), nullable=True),
    sa.Column('associated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_shipment_documents_shipment_id'), 'shipment_documents', ['shipment_id'], unique=False)
    op.create_table('shipment_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('ref_type', sa.Enum('BL', 'AWB', 'INVOICE', 'PO', 'CONTAINER', 'INTERNAL', name='referencetype'), nullable=False),
    sa.Column('ref_value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'ref_type', 'ref_value', name='uq_org_ref_type_value')
    )
    op.create_index(op.f('ix_shipment_references_shipment_id'), 'shipment_references', ['shipment_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'OPERATOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('email_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_record_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['email_record_id'], ['email_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('email_attachments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shipment_references_shipment_id'), table_name='shipment_references')
    op.drop_table('shipment_references')
    op.drop_index(op.f('ix_shipment_documents_shipment_id'), table_name='shipment_documents')
    op.drop_table('shipment_documents')
    op.drop_index(op.f('ix_ocr_results_document_id'), table_name='ocr_results')
    op.drop_table('ocr_results')
    op.drop_index(op.f('ix_email_records_org_id'), table_name='email_records')
    op.drop_table('email_records')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_classification_results_document_id'), table_name='classification_results')
    op.drop_table('classification_results')
    op.drop_index(op.f('ix_shipments_org_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_mailbox_connections_org_id'), table_name='mailbox_connections')
    op.drop_table('mailbox_connections')
    op.drop_index(op.f('ix_documents_shipment_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_org_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_activity_logs_shipment_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_org_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
